// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVXRaj8EKZXrSjDztfc8DmaNdx2ulqR84',
    appId: '1:327384831196:web:3ae303746681353f891019',
    messagingSenderId: '327384831196',
    projectId: 'rivan-5e684',
    authDomain: 'rivan-5e684.firebaseapp.com',
    storageBucket: 'rivan-5e684.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkou3miFEK3Z6oQlMCgo9ks69aZVZTZqQ',
    appId: '1:327384831196:android:361c60e66fc4dc03891019',
    messagingSenderId: '327384831196',
    projectId: 'rivan-5e684',
    storageBucket: 'rivan-5e684.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVXRaj8EKZXrSjDztfc8DmaNdx2ulqR84',
    appId: '1:327384831196:web:ca90834a69695106891019',
    messagingSenderId: '327384831196',
    projectId: 'rivan-5e684',
    authDomain: 'rivan-5e684.firebaseapp.com',
    storageBucket: 'rivan-5e684.firebasestorage.app',
  );

}