// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB59mNbnrfvyYw6_ZXDJ6xspa5bBoDo1jY',
    appId: '1:257914575293:web:8a68a29698a57437545ad4',
    messagingSenderId: '257914575293',
    projectId: 'project-cost-calculator-5c3be',
    authDomain: 'project-cost-calculator-5c3be.firebaseapp.com',
    storageBucket: 'project-cost-calculator-5c3be.firebasestorage.app',
    measurementId: 'G-SCQ4PGCX23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXNzMO1PA6tzLEmlmH-z5509fGtXHjomA',
    appId: '1:257914575293:android:2c8fc3cd5c32e0f9545ad4',
    messagingSenderId: '257914575293',
    projectId: 'project-cost-calculator-5c3be',
    storageBucket: 'project-cost-calculator-5c3be.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB59mNbnrfvyYw6_ZXDJ6xspa5bBoDo1jY',
    appId: '1:257914575293:web:74e53a70eb4971a8545ad4',
    messagingSenderId: '257914575293',
    projectId: 'project-cost-calculator-5c3be',
    authDomain: 'project-cost-calculator-5c3be.firebaseapp.com',
    storageBucket: 'project-cost-calculator-5c3be.firebasestorage.app',
    measurementId: 'G-FJKGGXZ9JL',
  );
}
